# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "public_network", ip: "192.168.0.50", bridge: "en0: Wi-Fi (AirPort)"
  config.vm.provision :shell, inline: "apt-get update && apt-get install nginx -y && service start nginx"
  config.vm.provider "virtualbox" do |v|
  v.name = "nginx_vm"
end
end
